apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: ocpnode-oq6l
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ocpnode-oq6l
    app.kubernetes.io/part-of: uthtest1
  name: ocpnode-oq6l
  namespace: utherp0-tenant
spec:
  ports:
  - port: 3001
    targetPort: 3001
  selector:
    app.kubernetes.io/instance: ocpnode-oq6l
status:
  loadBalancer: {}
